# Generated by Django 4.0.4 on 2022-04-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('tracker', '0001_initial'), ('tracker', '0002_pdtablefield_field_type'), ('tracker', '0003_pdrunlog'), ('tracker', '0004_pdrunlog_rows_added_pdrunlog_rows_deleted_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDTableField',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_id', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=200)),
                ('field_order', models.IntegerField()),
                ('label_en', models.CharField(max_length=200)),
                ('label_fr', models.CharField(max_length=200)),
                ('primary_key', models.BooleanField(default=False)),
                ('field_type', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['table_id', 'field_name', 'field_order'],
                'unique_together': {('table_id', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='PDRunLog',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_id', models.CharField(max_length=100)),
                ('file_from', models.CharField(max_length=200)),
                ('file_to', models.CharField(max_length=200)),
                ('activity_date', models.DateTimeField()),
                ('log_date', models.DateTimeField()),
                ('report_file', models.CharField(max_length=200)),
                ('rows_added', models.IntegerField(default=0)),
                ('rows_deleted', models.IntegerField(default=0)),
                ('rows_updated', models.IntegerField(default=0)),
            ],
        ),
    ]
